site_name: J & JJ Landscape
site_url: https://ericslusarz.github.io/Landscaping-Business-Blog-Documentation/
site_description: Project documentation with Markdown.
site_author: MkDocs Team

repo_url: https://ericslusarz.github.io/Landscaping-Business-Blog-Documentation/
edit_uri: ""

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Home: index.md
    - Adding a Post: adding/adding-a-post.md
    - Writing A Post: writing/writing-a-post.md


extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: ÔÉÅ
    - admonition
    - def_list
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs

copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.
google_analytics: ['UA-27795084-5', 'mkdocs.org']

plugins:
    - search

